**Presented by: Reza Saadatyar (2024-2025)**<br/>
**E-mail: Reza.Saadatyar@outlook.com**

**1️⃣ CPU (Central Processing Unit) & GPU (Graphics Processing Unit):**
- `CPU`
  - Designed for general-purpose computing.
  - Optimized for sequential tasks.
  - Has a few powerful cores.
  - Excellent at handling complex logic and single-threaded applications.
- `GPU`
  - Designed for parallel processing.
  - Has thousands of smaller, less powerful cores.
  - GPUs offer far faster numerical computing than CPUs.
  - Optimized for tasks that can be divided into many independent calculations.
  - Excellent for tasks like matrix operations, which are common in deep learning.

Putting a tensor on GPU using `to(device)` (e.g. `some_tensor.to(device)`) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. `some_tensor = some_tensor.to(device)`  

**2️⃣ N-d Tensor:** A tensor is a multi-dimensional array of numerical values. Tensor computation (like numpy) with strong GPU acceleration.
- `0-dimensional (Scalar):` A single number, e.g., 5, 3.14, -10. A <font color='red'><b>scalar</b></font> is a single number and in tensor-speak it's a zero dimension tensor.
- `1-dimensional (Vector):` A list of numbers, e.g., [1, 2, 3]. A <font color='blue'><b>vector</b></font> is a single dimension tensor but can contain many numbers.<br/>
- `2-dimensional (Matrix):` A table of numbers, e.g., [[1, 2], [3, 4]]. <font color='green'><b>MATRIX</b></font>  has two dimensions.
- `3-dimensional (or higher):` Like a "cube" of numbers or more complex higher-dimensional structures. These are common for representing images, videos, and more.

**3️⃣ Tensor datatypes:**<br/>
There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types). Some are specific for CPU and some are better for GPU.<br/>
Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).<br/>
The most common type (and generally the default) is `torch.float32` or `torch.float`.<br/>

**4️⃣ Getting information from tensors:**<br/>
* `shape` - what shape is the tensor? (some operations require specific shape rules)
* `dtype` - what datatype are the elements within the tensor stored in?
* `device` - what device is the tensor stored on? (usually GPU or CPU)

**5️⃣ Math Operations:**<br/>
* Addition ⇒ `a+b `or `torh.add(a, b)`
* Substraction ⇒ `a-b `or `torh.sub(a, b)`
* Multiplication (element-wise) ⇒ `a*b `
* Division ⇒ `a/b `or `torh.div(a, b)`
* Matrix multiplication ⇒ "`@`" in Python is the symbol for matrix multiplication. [`torch.matmul()`](https://pytorch.org/docs/stable/generated/torch.matmul.html) or [`torch.mm()`](https://pytorch.org/docs/stable/generated/torch.mm.html)
  
**6️⃣ Special Arrays**<br/>
- zeros
- ones
- empty
- eye
- full<br/>

Using [`torch.zeros_like(input)`](https://pytorch.org/docs/stable/generated/torch.zeros_like.html) or [`torch.ones_like(input)`](https://pytorch.org/docs/1.9.1/generated/torch.ones_like.html) which return a tensor filled with zeros or ones in the same shape as the `input` respectively.

**7️⃣ Random Arrays**
- `torch.rand:` Create a n*m tensor filled with random numbers from a uniform distribution on the interval [0, 1)
- `torch.randn:` Create a n*m tensor filled with random numbers from a normal distribution with mean 0 and variance 1. 
- `torch.randint:` Create a n*m tensor filled with random integers generated uniformly between low (inclusive) and high (exclusive).

`torch.randperm(value):` Create a random permutation of integers from 0 to value.<br/>
`torch.permute(input, dims):` Permute the original tensor to rearrange the axis order.

**8️⃣ Indexing & Slicing**
- `Indexing`
  - Accessing individual elements:  use integer indices to specify the position of the element you want to retrieve.
- `Slicing`
  - Extracting sub-tensors: Slicing allows you to extract a sub-part of your tensor by specifying a range of indices using the colon : operator.
    - `start:end` (exclusive end)
    - `start:` (from start to end of dimension)
    - `:end` (from beginning to end of dimension)
    - `:` (all elements)
    - `start:end:step` (start to end with given step)
  - Slicing with steps: You can include a step to skip elements in the slice. `start:end:step`

**9️⃣ `Unsqueeze & unsqueeze:`**
- The squeeze() method removes all singleton dimensions from a tensor. It will reduce the number of dimensions by removing the ones that have a size of 1.
- The unsqueeze() method adds a singleton dimension at a specified position in a tensor. It will increase the number of dimensions by adding a size of 1 dimension at a specific position.

**🔟 `PyTorch tensors & NumPy:`**
- [`torch.from_numpy(ndarray)`](https://pytorch.org/docs/stable/generated/torch.from_numpy.html)  NumPy array → PyTorch tensor
- [`torch.Tensor.numpy()`](https://pytorch.org/docs/stable/generated/torch.Tensor.numpy.html)  PyTorch tensor → NumPy array.

<font color='#FF000e' size="4.5" face="Arial"><b>Import modules</b></font>

In [2]:
import torch  #  torch.__version__  -> '2.5.1+cpu'
import numpy as np

<font color='#00ff0e' size="4.5" face="Arial"><b>CPU vs GPU</b></font>

In [3]:
# To check if you've got access to a Nvidia GPU, you can run `!nvidia-smi` where the `!` (also called bang) means
# "run this on the command line".
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [4]:
# torch.backends.mps.is_available() # Check for GPU on a Mac
torch.cuda.is_available()           # Check for GPU on Wind

False

In [5]:
# Set the device to 'cuda' (GPU) if a CUDA-compatible GPU is available, otherwise set it to 'cpu' (CPU)
# This is commonly used in PyTorch to ensure computations are performed on the GPU for faster processing when available
# device = "mps" if torch.backends.mps.is_available() else "cpu"
device = "cuda" if torch.cuda.is_available() else "cpu"  # Set device type
device_count =  torch.cuda.device_count()  # Count number of devices
print(f"{device = }, {device_count = }") 

device = 'cpu', device_count = 0


In [6]:
# Putting tensors (and models) on the GPU or CPU
tensor = torch.tensor([1, 2, 3]) # Create tensor (default on CPU)
tensor_on_gpu = tensor.to(device) # Move tensor to GPU (if available)
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()  # Moving tensors back to the CPU using .cpu().numpy()
tensor_on_gpu, tensor_back_on_cpu

(tensor([1, 2, 3]), array([1, 2, 3], dtype=int64))


<font color='#001240ee' size="4.5" face="Arial"><b>Scalar, Vector, Column vector, Matrix, & N-d Tensor</b></font>

In [7]:
# Create a 0-dimensional tensor (scalar) using PyTorch
# A 0D tensor represents a single value, similar to a scalar in mathematics
torch.tensor(4/3)

tensor(1.3333)

In [11]:
# Create a 1-dimensional tensor (vector) using PyTorch
# A 1D tensor is a list of values, similar to a vector in mathematics
a = torch.tensor([1, 2, 3])

# The `__class__` attribute shows the type of the object, which is `torch.Tensor`
print(f"{a = } --> {a.__class__ = }")

a = tensor([1, 2, 3]) --> a.__class__ = <class 'torch.Tensor'>


In [12]:
# Create a 2-dimensional tensor (column vector) using PyTorch
# A 2D tensor is a matrix with rows and columns
column_vector = torch.tensor([[1], [2], [3], [4]]) # This results in a column vector with 4 rows and 1 column
print(column_vector)

tensor([[1],
        [2],
        [3],
        [4]])


In [13]:
# Create a 2-dimensional tensor (matrix) using PyTorch
# A 2D tensor is a matrix with rows and columns
matrix = torch.tensor(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
print(matrix) # The resulting tensor is a 2D tensor with shape (3, 3), representing a 3x3 matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [14]:
# Create a 3-dimensional tensor using PyTorch
# A 3D tensor can be thought of as a collection of matrices (2D tensors) stacked along a third dimension
# Here, the tensor is created from a nested list structure with three levels:
# - The outer list represents the "depth" or "channels" (3 in this case).
# - The middle lists represent the rows of each matrix (2 in this case).
# - The inner lists represent the columns of each matrix (4 in this case).
tensor_3d = torch.tensor(
    [[[1, 2, 2, 5],
      [3, 4, 0, 8]],

     [[5, 6, 6, 7],
      [4, 8, 1, 2]],

     [[1, 1, 8, 9],
      [0, 0, 2, 3]]]
)

# The resulting tensor is a 3D tensor with shape (3, 2, 4), representing:
# - 3 matrices (depth/channels)
# - Each matrix has 2 rows and 4 columns
print(tensor_3d)

tensor([[[1, 2, 2, 5],
         [3, 4, 0, 8]],

        [[5, 6, 6, 7],
         [4, 8, 1, 2]],

        [[1, 1, 8, 9],
         [0, 0, 2, 3]]])


In [15]:
# Create a 4-dimensional tensor using PyTorch
# A 4D tensor can be thought of as a collection of 3D tensors stacked along a fourth dimension
# Here, the tensor is created from a nested list structure with four levels:
# - The outer list represents the "batch" dimension (1 in this case).
# - The next level represents the "depth" or "channels" (2 in this case).
# - The next level represents the rows of each matrix (2 in this case).
# - The innermost lists represent the columns of each matrix (4 in this case).
tensor_4d = torch.tensor(
    [[[[1, 2, 5, 4],
       [3, 4, 1, 0]],
      [[5, 6, 2, 3],
       [7, 8, 6, 4]]]]
)

# The resulting tensor is a 4D tensor with shape (1, 2, 2, 4), representing:
# - 1 batch
# - 2 channels/depth
# - Each channel has 2 rows and 4 columns
print(tensor_4d)

tensor([[[[1, 2, 5, 4],
          [3, 4, 1, 0]],

         [[5, 6, 2, 3],
          [7, 8, 6, 4]]]])


<font color='#ff555e2' size="4.5" face="Arial"><b>Getting information from tensors</b></font>

In [16]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([1.0, 5.0, 6.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.dtype, float_32_tensor.device

(torch.float32, device(type='cpu'))

In [17]:
# Create a 0-dimensional tensor (scalar) using PyTorch
# A 0D tensor represents a single value, similar to a scalar in mathematics
# The tensor is explicitly set to have a data type of `torch.float64` (64-bit floating point) and is placed on the CPU
a = torch.tensor(4/3, dtype=torch.float64, device="cpu")

# Print the tensor and its properties:
# - `a.shape`: The shape of the tensor (empty tuple for 0D tensors)
# - `a.ndim`: The number of dimensions (0 for a scalar)
# - `a.size()`: The size of the tensor (same as shape for 0D tensors)
print(f"{a = } --> {a.shape = }, {a.ndim = }, {a.size() = }")

# Convert the tensor to a different data type, `torch.float16` (16-bit floating point)
# This reduces the precision of the tensor but can save memory and improve performance
a_float16 = a.type(torch.float16)
# Alternatively, you can use `a.short()` to convert to a 16-bit integer, but this is not applicable here since the tensor is floating-point

a = tensor(1.3333, dtype=torch.float64) --> a.shape = torch.Size([]), a.ndim = 0, a.size() = torch.Size([])


In [18]:
# Create a tuple of tuples, where each inner tuple contains two integers
a = tuple([(1, 2), (3, 4), (5, 6)])
tensor_a = torch.tensor(a) # Convert the tuple of tuples into a PyTorch tensor
print(tensor_a) # The resulting tensor is a 2D tensor with shape (3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


<font color="#ff0051e2" size="4.5" face="Arial"><b>Math Operations</b></font>

In [19]:
# Create a 1-dimensional tensor (vector) with integer values
a = torch.tensor([1, 2, 3])

# Convert the tensor to `float` type using `.float()` to ensure the mean is computed as a floating-point value
mean_value = a.float().mean() # Calculate the mean of the tensor

# Convert the tensor to `torch.float32` type using `.type(torch.float32)` to ensure the standard deviation is computed as a floating-point value
std_value = a.type(torch.float32).std() # Calculate the standard deviation of the tensor
print(f"Mean: {mean_value}, Standard Deviation: {std_value}")

Mean: 2.0, Standard Deviation: 1.0


In [20]:
# Create two 2D tensors (matrices) with random integer values between 0 and 10
a = torch.randint(10, (2, 2))  # 2x2 tensor
b = torch.randint(10, (2, 2))  # 2x2 tensor
a, b

(tensor([[3, 6],
         [5, 0]]),
 tensor([[3, 2],
         [7, 9]]))

In [21]:
# Adds corresponding elements of `a` and `b`
# Subtracts elements of `b` from corresponding elements of `a`
torch.add(a, b, ), torch.sub(a, b, )

(tensor([[ 6,  8],
         [12,  9]]),
 tensor([[ 0,  4],
         [-2, -9]]))

In [22]:
# Element-wise multiplication using `*` (Multiplies corresponding elements of `a` and `b`)
elementwise_mul = a * b

# Matrix multiplication using `@` (Performs matrix multiplication of `a` and `b`)
matrix_mul = a @ b

# Matrix multiplication using `torch.matmul()` (Performs matrix multiplication of `a` and `b`)
matmul_result = torch.matmul(a, b)

print(f"Element-wise multiplication:\n{elementwise_mul}")
print(f"Matrix multiplication (using @):\n{matrix_mul}")
print(f"Matrix multiplication (using torch.matmul):\n{matmul_result}")

Element-wise multiplication:
tensor([[ 9, 12],
        [35,  0]])
Matrix multiplication (using @):
tensor([[51, 60],
        [15, 10]])
Matrix multiplication (using torch.matmul):
tensor([[51, 60],
        [15, 10]])


In [23]:
# Perform element-wise division of two 2D tensors `a` and `b`
a = torch.randint(10, (2, 2))  # 2x2 tensor with random integer values between 0 and 10
b = torch.randint(1, 10, (2, 2))  # 2x2 tensor with random integer values between 1 and 10 (to avoid division by zero)

# Element-wise division using `/` (Divides corresponding elements of `a` by `b`)
elementwise_div = a / b
print(f"Element-wise division:\n{elementwise_div}")

Element-wise division:
tensor([[0.4000, 1.2500],
        [4.0000, 4.0000]])


<font color="#00ff21aa" size="4.5" face="Arial"><b>Special Arrays</b></font>

In [25]:
# Create a 2D tensor filled with ones using PyTorch
torch.ones((2, 1))  # The tensor has a shape of (2, 1), meaning it has 2 rows and 1 column

tensor([[1.],
        [1.]])

In [26]:
# Create a 3D tensor filled with zeros using PyTorch
# The tensor has a shape of (3, 4, 3), meaning:
# - 3 matrices (depth/channels)
# - Each matrix has 4 rows and 3 columns
torch.zeros((3, 4, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [27]:
# The tensor has a shape of (5, 4), meaning it has 5 rows and 4 columns
torch.eye(5, 4) # The diagonal elements are set to 1, and all other elements are set to 0

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [28]:
# The tensor has a shape of (4, 3), meaning it has 4 rows and 3 columns
torch.full([4, 3], fill_value=2) # All elements in the tensor are set to the `fill_value` (2 in this case)

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

<font color="#22aa1232" size="4.5" face="Arial"><b>Random Arrays</b></font>

In [101]:
torch.manual_seed(12) # Set a manual seed for reproducibility
torch.rand((4, 3)) # Create a 2D tensor with random values uniformly distributed between 0 and 1 (shape of (4, 3))

tensor([[0.4657, 0.2328, 0.4527],
        [0.5871, 0.4086, 0.1272],
        [0.6373, 0.2421, 0.7312],
        [0.7224, 0.1992, 0.6948]])

In [29]:
# Set a manual seed for reproducibility
torch.manual_seed(12)

# Create a 2D tensor with random integer values within a specified range
# The range is from 2 (inclusive) to 13 (exclusive)
torch.randint(2, 13, (4, 3)) # The tensor has a shape of (4, 3), meaning it has 4 rows and 3 columns

tensor([[12,  3,  9],
        [11,  2, 10],
        [ 8,  3,  3],
        [10, 11,  2]])

<font color="#22aa1232" size="4.5" face="Arial"><b>Randperm & permute</b></font>

In [98]:
# Create a random permutation of integers from 0 to 9
torch.randperm(10)

tensor([3, 8, 7, 6, 4, 5, 2, 9, 1, 0])

In [30]:
# Create a tensor with a specific shape (224, 224, 3) using random values
# This shape is commonly used for RGB images, where:
# - 224 is the height
# - 224 is the width
# - 3 is the number of color channels (Red, Green, Blue)
original = torch.rand(size=(224, 224, 3))

# Permute the tensor to rearrange the order of its axes
# The `permute()` method reorders the dimensions of the tensor
# Here, the new order is (2, 0, 1), which means:
# - The original axis 2 (channels) becomes the new axis 0
# - The original axis 0 (height) becomes the new axis 1
# - The original axis 1 (width) becomes the new axis 2
permuted = original.permute(2, 0, 1)

# Print the shapes of the original and permuted tensors
print(f"Previous shape: {original.shape}")
print(f"New shape: {permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


<font color="#bb1254ff" size="4.5" face="Arial"><b>Indexing & Slicing</b></font>

In [32]:
# Create a 1D tensor with 12 random values from a standard normal distribution (mean=0, std=1)
a = torch.randn(12)
print(f"a: {a}")
print(f"a[0:1]: {a[0:1]}") # A slice of the tensor containing the first element (as a 1D tensor)
print(f"a[0]: {a[0]}")     # The first element of the tensor (as a scalar)
print(f"a[[0, 2, 7]]: {a[[0, 2, 7]]}") # A tensor containing the elements at indices 0, 2, and 7

a: tensor([ 1.1538,  0.3991,  0.2250,  0.2924,  0.0614, -0.2668, -1.3685, -1.1728,
         0.1342, -0.2616, -1.5436,  0.2017])
a[0:1]: tensor([1.1538])
a[0]: 1.1538151502609253
a[[0, 2, 7]]: tensor([ 1.1538,  0.2250, -1.1728])


In [33]:
# `a[2:12:2]`: Slice the tensor from index 2 to index 12 (exclusive) with a step of 2
# `a[2::2]`: Slice the tensor from index 2 to the end with a step of 2
a[2:12:2], a[2::2]

(tensor([ 0.2250,  0.0614, -1.3685,  0.1342, -1.5436]),
 tensor([ 0.2250,  0.0614, -1.3685,  0.1342, -1.5436]))

In [34]:
a = torch.randn(3,5)
a[0:3, 2:-1], a[:, 2:-1]

(tensor([[ 0.6282,  1.0835],
         [-1.4616, -0.2670],
         [-0.8549,  0.1933]]),
 tensor([[ 0.6282,  1.0835],
         [-1.4616, -0.2670],
         [-0.8549,  0.1933]]))

(tensor([[ 1.0210,  0.9056],
         [ 1.0438,  0.3598],
         [-0.3547, -0.2390]]),
 tensor([[ 1.0210,  0.9056],
         [ 1.0438,  0.3598],
         [-0.3547, -0.2390]]))

In [45]:
a[0:2], a[0:2, :]

(tensor([[ 0.3641,  0.4331,  0.5895, -1.2568,  0.4411],
         [-0.2782, -0.2588, -0.4724,  1.0558,  0.5683]]),
 tensor([[ 0.3641,  0.4331,  0.5895, -1.2568,  0.4411],
         [-0.2782, -0.2588, -0.4724,  1.0558,  0.5683]]))

In [46]:
a[::2, 2:]

tensor([[ 0.5895, -1.2568,  0.4411],
        [ 1.9573, -0.3660, -0.2266]])

In [51]:
a = torch.randn(4, 6, 7)
a

tensor([[[ 4.2969e-01,  1.1980e+00, -1.0833e+00,  3.5402e-01,  7.9477e-01,
           2.3819e+00, -3.7064e-01],
         [-7.9222e-01, -8.3236e-01, -3.2613e-01,  1.7579e+00,  3.6650e-01,
          -3.3034e-02, -1.3126e+00],
         [-9.2532e-01, -3.8545e-01, -5.3512e-01,  4.0278e-01,  1.1849e-01,
           2.9048e+00,  1.4602e+00],
         [ 1.5539e+00, -1.5911e+00, -2.1023e-01, -9.3761e-01,  5.8109e-01,
          -2.9350e-01, -8.0874e-01],
         [-3.1397e-01, -1.9417e+00, -1.8543e+00,  2.7558e-01, -5.9811e-01,
          -3.8076e-01,  3.5677e-03],
         [ 2.4633e-01,  1.3368e-01, -1.0755e+00,  1.9913e+00, -1.4785e+00,
          -1.3697e+00, -5.6596e-01]],

        [[ 1.1672e+00, -1.7709e+00, -4.4624e-01,  7.9434e-01,  7.4588e-01,
           3.8383e-01,  4.3685e-01],
         [ 8.1806e-01, -1.0156e+00, -5.4061e-01,  1.5879e-01, -4.2923e-01,
           4.3937e-01, -1.3256e-01],
         [ 1.7277e+00,  9.3084e-01,  1.4519e+00, -4.9755e-01,  6.5133e-01,
          -2.1107e-01,  2.7

In [54]:
a[1:2, 3:5, 2:4], a[[1], 3:5, 2:4], a[1, 3:5, 2:4]

(tensor([[[ 0.8959,  2.1258],
          [ 0.3422, -2.3196]]]),
 tensor([[[ 0.8959,  2.1258],
          [ 0.3422, -2.3196]]]),
 tensor([[ 0.8959,  2.1258],
         [ 0.3422, -2.3196]]))

In [56]:
a[1], a[:, :, -1], a[..., -1]

(tensor([[ 1.1672, -1.7709, -0.4462,  0.7943,  0.7459,  0.3838,  0.4369],
         [ 0.8181, -1.0156, -0.5406,  0.1588, -0.4292,  0.4394, -0.1326],
         [ 1.7277,  0.9308,  1.4519, -0.4976,  0.6513, -0.2111,  0.2740],
         [-1.1969, -0.6086,  0.8959,  2.1258, -0.0277,  0.3838, -1.7151],
         [ 0.4147,  0.8398,  0.3422, -2.3196,  0.7623,  0.6204,  0.2301],
         [-1.7236,  0.7523, -0.5669,  0.7961, -0.3546, -1.5467,  0.5208]]),
 tensor([[-0.3706, -1.3126,  1.4602, -0.8087,  0.0036, -0.5660],
         [ 0.4369, -0.1326,  0.2740, -1.7151,  0.2301,  0.5208],
         [ 0.6081,  1.2861,  0.9130, -0.4712,  0.0920,  1.1607],
         [ 1.1845, -0.2007, -0.2161,  0.1180,  1.2937,  0.7572]]),
 tensor([[-0.3706, -1.3126,  1.4602, -0.8087,  0.0036, -0.5660],
         [ 0.4369, -0.1326,  0.2740, -1.7151,  0.2301,  0.5208],
         [ 0.6081,  1.2861,  0.9130, -0.4712,  0.0920,  1.1607],
         [ 1.1845, -0.2007, -0.2161,  0.1180,  1.2937,  0.7572]]))

<font color="#aaff5499" size="4.5" face="Arial"><b>Unsqueeze & squeeze</b></font>

In [71]:
# Removing all singleton dimensions
tensor_a = torch.randn(1, 3, 1, 4, 1)
print("Original shape of tensor_a:", tensor_a.shape)  # Output: torch.Size([1, 3, 1, 4, 1])

tensor_b = tensor_a.squeeze()
print("Squeezed shape of tensor_b:", tensor_b.shape)  # Output: torch.Size([3, 4])

Original shape of tensor_a: torch.Size([1, 3, 1, 4, 1])
Squeezed shape of tensor_b: torch.Size([3, 4])


In [104]:
# Removing a specific singleton dimension
a = torch.randn(2, 1, 3, 1, 4)
print("Original shape of a:", a.shape)  # Output: torch.Size([2, 1, 3, 1, 4])

# Remove the first dimension (index 0) which is not 1, so no change is done; Output: torch.Size([2, 1, 3, 1, 4])
print(f"{a.squeeze(0).shape = }")

# Remove the second dimension (index 1) which is size 1; Output: torch.Size([2, 3, 1, 4])
print(f"{a.squeeze(1).shape = }")

# Remove the fourth dimension (index 3) which is size 1; Output: torch.Size([2, 1, 3, 4])
print(f"{a.squeeze(3).shape = }")

print(f"{a.squeeze().shape = }")

Original shape of a: torch.Size([2, 1, 3, 1, 4])
a.squeeze(0).shape = torch.Size([2, 1, 3, 1, 4])
a.squeeze(1).shape = torch.Size([2, 3, 1, 4])
a.squeeze(3).shape = torch.Size([2, 1, 3, 4])
a.squeeze().shape = torch.Size([2, 3, 4])


In [103]:
b = torch.randn(2, 2)
print("Original:", b)  # Output: torch.Size([3, 4])

# Add dimension at the beginning (index 0); # Output: torch.Size([1, 3, 4])
print(f"{b.unsqueeze(0) = } --> {b.unsqueeze(0).shape = }")
# Add dimension in between the two dimensions (index 1); Output: torch.Size([3, 1, 4])
print(f"{b.unsqueeze(1) = } --> {b.unsqueeze(1).shape = }")

# Add dimension at the end (index 2); Output: torch.Size([3, 4, 1])
print(f"{b.unsqueeze(2) = } --> {b.unsqueeze(2).shape = }")

Original: tensor([[ 0.8279,  1.1309],
        [-0.8629,  2.1094]])
b.unsqueeze(0) = tensor([[[ 0.8279,  1.1309],
         [-0.8629,  2.1094]]]) --> b.unsqueeze(0).shape = torch.Size([1, 2, 2])
b.unsqueeze(1) = tensor([[[ 0.8279,  1.1309]],

        [[-0.8629,  2.1094]]]) --> b.unsqueeze(1).shape = torch.Size([2, 1, 2])
b.unsqueeze(2) = tensor([[[ 0.8279],
         [ 1.1309]],

        [[-0.8629],
         [ 2.1094]]]) --> b.unsqueeze(2).shape = torch.Size([2, 2, 1])


<font color='#hh99gg99' size='4.5' face="Arial"><b>PyTorch tensors & NumPy</b></font>

In [28]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
nump = torch.Tensor.numpy(tensor)
array, tensor, nump

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))